name: dart_meteor
description: Meteor client blinding for dart and flutter
version: 1.0.0
homepage: https://github.com/tanutapi/dart_meteor
author: Tanut Apiwong <tanutapi@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  crypto: ^2.0.6
  rxdart: ^0.22.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
