name: dart_meteor_web
description: This library make connection between meteor backend and flutter web app easily. Design to work seamlessly with StreamBuilder and FutureBuilder.
version: 1.0.8
homepage: https://github.com/tanutapi/dart_meteor/tree/web

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  crypto: ^2.0.6
  rxdart: ^0.22.6
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
