name: Testing

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    container: 
      image: docker
    steps:
      - run: |
          apt-get install git -y
          git clone https://github.com/tanutapi/simple-meteor-chat.git
          cd simple-meteor-chat
          docker-compose up
    
  test:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
